### ISSUE TITLE
Keyboard Shortcut not working

### ISSUE THREAD

**Issue by dannyconnell** [lumaxis/snippet-copy#10]
Hi there. Great extension, it's just what I need right now! 👍

However the keyboard shortcut is not working for me. Perhaps it's clashing with something else?

Could you please add the option to change the keyboard shortcut?

**Comment by dannyconnell** [comment]
Never mind, I just realised you can add a keyboard shortcut for any registered command. Closing. Great work!!

**Comment by lumaxis** [comment]
@dannyconnell Thanks! If you have suggestions for a different default keyboard shortcut, I'm all ears.
I chose the current one mostly because I wanted something close to Ctrl/Cmd+C but I realize that the current default is not super ergonomical to perform, so I'd love to hear what you're using.

**Comment by dannyconnell** [comment]
I’m using Cmd+Ctrl+Shift+C. Also not the easiest to perform and wouldn’t translate well to Windows. However it works for me. 👍

**Comment by lumaxis** [comment]
Cool, thanks! You might be interested in this change here then: https://github.com/lumaxis/snippet-copy/pull/9/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R56-R60
The next version adds a new command to automatically surround the snippet with Markdown code block syntax like this:
````markdown
```
<your snippet>
```
````

**Comment by lumaxis** [comment]
And the default keyboard shortcut for that will be Cmd+Ctrl+Shift+C, so would conflict with your current setting.

**Comment by dannyconnell** [comment]
Ooh that’s handy, cheers! Maybe I’ll go with Cmd Shift Ctrl Alt C for that 😂
