### ISSUE TITLE
Paste will clear the format of vscode (color highlight)

### ISSUE THREAD

**Issue by FateArth** [lumaxis/snippet-copy#297]
The function of this plug-in is great, but I need a function. I want to add a choice. You can set that canceling pasting will clear the format of vscode by default (color highlight)

**Comment by lumaxis** [comment]
@FateArth Apologies, I missed your issue for all this time!

Are you still interested in this feature? Could you elaborate what exactly you are looking for, I'm not sure I properly understand.
